### ISSUE TITLE
Can ui-predicate-vue be installed from composer?

### ISSUE THREAD

**Issue by jonnybradley** [FGRibreau/ui-predicate#78]
### Prerequisites
 - [x] I have read the [Contributing guidelines](https://github.com/fgribreau/ui-predicate/blob/master/.github/CONTRIBUTING.md)
 - [x] I have read the [Code of conduct](https://github.com/fgribreau/ui-predicate/blob/master/.github/CODE_OF_CONDUCT.md) and I agree with it

### Description
Is there a built version of ui-predicate-vue somewhere we can include in [our project](https://tiki.org) using composer?

#### For Example
It would be nice if
```
https://asset-packagist.org/package/npm-asset/ui-predicate-vue
```
contained `packages/ui-predicate-vue/lib/ui-predicate-vue.js` and `packages/ui-predicate-vue/lib/ui-predicate-vue.css`

TIA

**Comment by FGRibreau** [comment]
I will gladly accept a PR for this :)
